name: Gatsby Publish

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Node Config
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: enriikke/gatsby-gh-pages-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          access-token: ${{ secrets.cristhIAn }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths