name: Gatsby Publish

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Node Config
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: peaceiris/actions-gh-pages@v3
        with:
          access-token: ${{ secrets.cristhIAn }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: www.cristhianwiki.com
